
name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Adjust if needed

    # Build C# solution
    - name: Build C# code
      run: dotnet build DotnetTemplate.sln

    # Run C# tests
    - name: Run C# tests
      run: dotnet test DotnetTemplate.Web.Tests/DotnetTemplate.Web.Tests.csproj

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Adjust if needed

    # Install dependencies
    - name: Install TypeScript dependencies
      run: npm install

    # Build TypeScript code
    - name: Build TypeScript
      run: npm run build

    # Run TypeScript linter
    - name: Run linter
      run: npm run lint

    # Run TypeScript tests
    - name: Run TypeScript tests
      run: npm test
